# Generated by Django 4.2.4 on 2023-08-05 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User uuid who create records.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User uuid who updated record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when records created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when records updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when records created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when records updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='blog_app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
