# Generated by Django 4.2.4 on 2023-08-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Blog - Like', 'verbose_name_plural': 'Blog - Like'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Blog - Posts', 'verbose_name_plural': 'Blog - Posts'},
        ),
    ]
